---
title: "Tarea 1"
author: "Daniel Czarnievicz"
date: "September 10, 2018"
output: 
      pdf_document:
            number_sections: true
            toc: false
geometry: margin=3cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
options(xtable.comment = FALSE)
library(tidyverse)
library(xtable)
```

# Introducción

Simularemos los datos
$$N \sim Po(90) \:\:\: \text{cantidad de puntos}$$
$$x_i \sim Unif(0, \, 1) \:\:\: \text{N observaciones}$$
$$y_i \sim Unif(0, \, 1) \:\:\: \text{N observaciones}$$

Se puede acceder al repositorio donde se encuentra el código haciendo click [aqui](https://github.com/daczarne/rep_research/tree/master/Rmarkdown)

<!--
2. Tabla con un resumen de los datos simulados  
      - Usa `xtable()` para la tabla  
      - incluir un título de la tabla, que salga arriba en el documento final  
      - incluir una etiqueta para poder referenciar la tabla en el texto  

3. Completar la frase: “En la Tabla REF se observa que la mediana de las $x$ es —–”
de forma que el valor de la mediana se complete automáticamente cuando cambian
los datos.
-->

# Simulaciones y tabla

```{r simdatos, cache=TRUE}
N <- rpois(1, lambda=90)
x_i <- runif(N, min=0, max=1)
y_i <- runif(N, min=0, max=1)
datos <- as_tibble(cbind(x_i, y_i))
```

```{r mytable, results='asis', message=FALSE, echo=FALSE, comment=""}
a <- unclass(summary(datos))
dim(a) <- NULL
b <- sub(":.*", "", a)
a <- as.numeric(sub(".*:", "", a))
dim(a) <- c(6,2)
row.names(a) <- unique(b)
colnames(a) <- c("X", "Y")
print(xtable::xtable(a, caption="Resumen de las variables X e Y", digits=4, label="tab:mytable"), type="latex")
```

En la Tabla \ref{tabe:mytable} se observa que la mediana de las $x$ es `r round(median(datos$x_i), 4)`.

# Figura

```{r, fig.cap="A figure"}
datos %>%
      ggplot() +
      geom_point(aes(x_i, y_i)) +
      labs(x="X", y="Y") +
      theme(axis.ticks=element_blank())
```

